In [1]:
import numpy as np

In [2]:
#activation function
def sigmoid(x):
    return(1/(1+np.exp(-x)))

In [3]:
def s_der(x):
    return (x*(1-x))

In [4]:
# inputs
input = np.array(
    [
        [1,0,1],
        [1,1,1],
        [0,1,1],
        [0,0,1]
    ]
)

In [5]:
t_output = np.array([[1,1,0,0]]).T
t_output

array([[1],
       [1],
       [0],
       [0]])

In [6]:
t_out = np.array([
    [1],
    [1],
    [0],
    [0]
]
)
t_out

array([[1],
       [1],
       [0],
       [0]])

In [7]:
weights = 2*np.random.random((3,1)) - 1
weights

array([[-0.56057552],
       [ 0.93487929],
       [-0.73583384]])

In [8]:
for iter in range(1):
    output = sigmoid(np.dot(input, weights))

In [13]:
for i in range(10000):
    output = sigmoid(np.dot(input, weights))
    error = t_output-output
    upd = error*s_der(output)
    weights += np.dot(input.T, upd)

In [14]:
np.round(output)

array([[1.],
       [1.],
       [0.],
       [0.]])

In [15]:
output

array([[0.99359114],
       [0.99212315],
       [0.00786222],
       [0.00965989]])

In [16]:
sigmoid(6459000000000)

1.0